kinect2_bridge:
  image_publisher_options:
    IR_SD:
      image_type: "IR_SD"
      publish: false
      publish_compressed: false
    IR_SD_RECT:
      image_type: "IR_SD_RECT"
      publish: false
      publish_compressed: false
    DEPTH_SD:
      image_type: "DEPTH_SD"
      publish: false
      publish_compressed: false
    DEPTH_SD_RECT:
      image_type: "DEPTH_SD_RECT"
      publish: false
      publish_compressed: false
    DEPTH_QHD:
      image_type: "DEPTH_QHD"
      publish: false
      publish_compressed: false
    DEPTH_HD:
      image_type: "DEPTH_HD"
      publish: true
      publish_compressed: false
    COLOR_SD_RECT:
      image_type: "COLOR_SD_RECT"
      publish: false
      publish_compressed: false
    COLOR_QHD_RECT:
      image_type: "COLOR_QHD_RECT"
      publish: false
      publish_compressed: false
    COLOR_HD_RECT:
      image_type: "COLOR_HD_RECT"
      publish: false
      publish_compressed: false
    COLOR_HD:
      image_type: "COLOR_HD"
      publish: true
      publish_compressed: false
    MONO_QHD:
      image_type: "MONO_QHD"
      publish: false
      publish_compressed: false
    MONO_QHD_RECT:
      image_type: "MONO_QHD_RECT"
      publish: false
      publish_compressed: false
    MONO_HD_RECT:
      image_type: "MONO_HD_RECT"
      publish: false
      publish_compressed: false
    MONO_HD:
      image_type: "MONO_HD"
      publish: false
      publish_compressed: false
  colorParams:
    fx: 1081.37
    fy: 1081.37
    cx: 959.5
    cy: 539.5
  irParams:
    fx: 366.781
    fy: 366.781
    cx: 254.3
    cy: 203.045
    k1: 0.0857434
    k2: -0.270673
    k3: 0.102812
    p1: 0.0
    p2: 0.0
    